# Generated by Django 4.2.7 on 2024-03-20 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(choices=[('A1B.E. Chemical', 'Be Chemical'), ('A2B.E. Civil', 'Be Civil'), ('A3B.E. Electrical & Electronics', 'Be Electrical'), ('A4B.E. Mechanical', 'Be Mechanical'), ('A5B. Pharma', 'B Pharma'), ('A7B.E. Computer Science', 'Be Cs'), ('A8B.E. Electronics and Instrumentation', 'Be Electronics'), ('A9B.E. Biotechnology', 'Be Biotech'), ('AAB.E. Electronics & Communication', 'Be Electronics Comm'), ('ABB.E. Manufacturing Engineering', 'Be Manufacturing'), ('B1M.Sc. Biological Sciences', 'M Sc Bio'), ('B2M.Sc. Chemistry', 'M Sc Chem'), ('B3M.Sc. Economics', 'M Sc Econ'), ('B4M.Sc. Mathematics', 'M Sc Math'), ('B5M.Sc. Physics', 'M Sc Physics'), ('C2M.Sc. General Studies', 'M Sc General'), ('C5M.Sc. Engineering Technology', 'M Sc Tech'), ('C6M.Sc. Information Systems', 'M Sc Info Sys'), ('C7M.Sc. Finance', 'M Sc Finance')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.dept')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='dept',
            field=models.ManyToManyField(through='student.CDC', to='student.dept'),
        ),
        migrations.AddField(
            model_name='course',
            name='ic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(through='student.CourseEnrollment', to='student.student'),
        ),
        migrations.AddField(
            model_name='cdc',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course'),
        ),
        migrations.AddField(
            model_name='cdc',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.dept'),
        ),
    ]
