# Generated by Django 4.2.7 on 2024-03-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='uid',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
