# Generated by Django 4.2.7 on 2024-03-20 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0003_alter_course_ic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ic',
            field=models.OneToOneField(limit_choices_to={'groups__name': 'prof'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
