# Generated by Django 4.2.7 on 2024-03-20 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_course_ic'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.dept'),
        ),
    ]
