# Generated by Django 4.2.7 on 2024-03-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_professor_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cdc_added',
            field=models.BooleanField(default=False),
        ),
    ]
