# Generated by Django 4.2.7 on 2024-03-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_cdc_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdc',
            name='sem',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='units',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='student',
            name='sem',
            field=models.IntegerField(default=0),
        ),
    ]
