# Generated by Django 4.2.7 on 2024-03-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_cdc_sem_course_units_student_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.IntegerField(default=1),
        ),
    ]
