# Generated by Django 4.2.7 on 2024-03-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_announcement_content_announcement_date_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to='course_image'),
        ),
    ]
