# Generated by Django 4.2.7 on 2024-03-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_alter_courseenrollment_grade_evaluative_evalgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluative',
            name='info',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
