# Generated by Django 4.2.7 on 2024-03-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_evaluative_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdf_files')),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='pdf_files',
            field=models.ManyToManyField(blank=True, null=True, to='student.pdffile'),
        ),
    ]
