# Generated by Django 4.2.7 on 2024-03-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_pdffile_announcement_pdf_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='pdf_files',
            field=models.ManyToManyField(blank=True, to='student.pdffile'),
        ),
    ]
