# Generated by Django 4.2.7 on 2024-03-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_alter_announcement_pdf_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='pdf_files',
        ),
        migrations.AddField(
            model_name='announcement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='pdf_files'),
        ),
    ]
