# Generated by Django 4.2.7 on 2024-03-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_remove_announcement_pdf_files_announcement_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFFile',
        ),
    ]
